import{useEffect,useState}from'react';import{ArrowLeft,Copy,Gamepad2,History,LogOut,Plus,Settings,Shield,Users,Volume2}from'lucide-react';
import{createRoom,getHistory,getRoom,inviteUrl,joinRoom,saveTeam,shareOrigin,wsUrl}from'./api';import type{Room,Team}from'./types';import{GameField}from'./GameField';

const roomFromUrl=()=>{const code=new URLSearchParams(location.search).get('room')?.toUpperCase().replace(/[^A-F0-9]/g,'')||'';if(code.length===6){history.replaceState({},'',location.pathname);return code}return''};

const activeRoomKey='activeRoom';
const storedActiveRoom=()=>localStorage.getItem(activeRoomKey)||'';
const persistActiveRoom=(code:string)=>localStorage.setItem(activeRoomKey,code);
const clearActiveRoom=()=>localStorage.removeItem(activeRoomKey);

const newTeam=():Team=>({name:'',short:'',primary:'#6d28d9',secondary:'#fbbf24',players:['','','',''],playerPhotos:['','','','']});
const teamStorageKey=(token:string)=>`team:${token}`;
const storedTeam=(token:string|null):Team|null=>{if(!token)return null;try{const value=localStorage.getItem(teamStorageKey(token));if(!value)return null;const team=JSON.parse(value) as Team;return{...team,playerPhotos:team.playerPhotos||['','','','']}}catch{return null}};
const resizePhoto=(file:File)=>new Promise<string>((resolve,reject)=>{const image=new Image();const url=URL.createObjectURL(file);image.onload=()=>{const size=128;const canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const context=canvas.getContext('2d')!;const source=Math.min(image.naturalWidth,image.naturalHeight);context.drawImage(image,(image.naturalWidth-source)/2,(image.naturalHeight-source)/2,source,source,0,0,size,size);URL.revokeObjectURL(url);resolve(canvas.toDataURL('image/jpeg',.75))};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Não foi possível abrir essa imagem'))};image.src=url});
const playerId=()=>{const webCrypto=globalThis.crypto;if(typeof webCrypto?.randomUUID==='function')return webCrypto.randomUUID();if(typeof webCrypto?.getRandomValues==='function'){const bytes=webCrypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const hex=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');return`${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`}return`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`};
type Screen='auth'|'home'|'team'|'join'|'lobby'|'game'|'result'|'history';
const screenFromRoom=(room:Room):Screen=>room.status==='finished'?'result':room.match?'game':'lobby';
export function App(){
 const[user,setUser]=useState(()=>localStorage.getItem('name')||'');const[team,setTeam]=useState<Team|null>(()=>storedTeam(localStorage.getItem('token')));const[pendingCode,setPendingCode]=useState(roomFromUrl);const[screen,setScreen]=useState<Screen>(()=>{if(!localStorage.getItem('name'))return'auth';if(pendingCode)return'join';if(storedActiveRoom())return'lobby';return storedTeam(localStorage.getItem('token'))?'home':'team'});const[room,setRoom]=useState<Room|null>(null);const[ws,setWs]=useState<WebSocket|null>(null);const[restoring,setRestoring]=useState(()=>!!storedActiveRoom()&&!!localStorage.getItem('name')&&!pendingCode);const[creating,setCreating]=useState(false);const[joining,setJoining]=useState(false);const[savingTeam,setSavingTeam]=useState(false);const[toast,setToast]=useState('');
 useEffect(()=>{if(!pendingCode||!user||!team)return;setScreen('join')},[pendingCode,user,team]);
 useEffect(()=>{const code=storedActiveRoom();if(!code||!user||!team||pendingCode){setRestoring(false);return}let cancelled=false;getRoom(code).then(r=>{if(cancelled)return;setRoom(r);setScreen(screenFromRoom(r))}).catch(()=>{if(cancelled)return;clearActiveRoom();setScreen('home')}).finally(()=>{if(!cancelled)setRestoring(false)});return()=>{cancelled=true}},[user,team,pendingCode]);
 useEffect(()=>{if(!room||!['lobby','game','result'].includes(screen))return;const code=room.code;let socket:WebSocket|null=null;let retry:number|undefined;let active=true;const connect=()=>{if(!active)return;if(retry!==undefined){window.clearTimeout(retry);retry=undefined}socket=new WebSocket(wsUrl(code));socket.onopen=()=>{if(active&&socket)setWs(socket)};socket.onmessage=e=>{if(!active)return;const m=JSON.parse(e.data);if(m.type==='state'&&m.room?.code===code){setRoom(m.room);setScreen(screenFromRoom(m.room))}if(m.type==='error')flash(m.message)};socket.onclose=()=>{if(active)retry=window.setTimeout(connect,1200)}};connect();return()=>{active=false;if(retry!==undefined){window.clearTimeout(retry);retry=undefined}setWs(null);socket?.close()}},[room?.code,screen]);
 const flash=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2500)};
 const login=(name:string)=>{const clean=name.trim();if(clean.length<2)return;const token=`dev-${playerId()}`;localStorage.setItem('name',clean);localStorage.setItem('token',token);localStorage.removeItem('team');setUser(clean);setTeam(null);setScreen('team')};
 const logout=()=>{localStorage.removeItem('name');localStorage.removeItem('token');clearActiveRoom();setUser('');setTeam(null);setRoom(null);setWs(null);setScreen('auth')};
 const persistTeam=async(value:Team)=>{if(savingTeam)return;const token=localStorage.getItem('token');if(!token)return;setSavingTeam(true);try{const result=await saveTeam(user,value);const saved={...value,playerPhotos:result.player_photos};localStorage.setItem(teamStorageKey(token),JSON.stringify(saved));setTeam(saved);setScreen(pendingCode?'join':'home')}catch(e){flash((e as Error).message)}finally{setSavingTeam(false)}};
 const leaveRoom=()=>{clearActiveRoom();setRoom(null);setWs(null);setScreen('home')};
 const create=async()=>{if(creating)return;if(!team)return setScreen('team');setCreating(true);try{const r=await createRoom(user,team);persistActiveRoom(r.code);setRoom(r);setScreen('lobby')}catch(e){flash((e as Error).message)}finally{setCreating(false)}};
 const join=async(code:string)=>{if(joining||!team)return setScreen('team');setJoining(true);try{const r=await joinRoom(code.toUpperCase(),user,team);persistActiveRoom(r.code);setRoom(r);setScreen('lobby')}catch(e){flash((e as Error).message)}finally{setJoining(false)}};
 const nav=(s:Screen)=><button className="back" onClick={()=>setScreen(s)}><ArrowLeft/> Voltar</button>;
 return <div className="app">{toast&&<div className="toast">{toast}</div>}
 {restoring&&<main className="page narrow"><div className="panel empty"><p>Retomando partida...</p></div></main>}
 {!restoring&&screen==='auth'&&<Auth onLogin={login}/>} {!restoring&&screen==='home'&&team&&<><Header user={user} onLogout={logout}/><main className="page"><section className="hello"><div><span className="eyebrow">OLÁ, {user.toUpperCase()}!</span><h1>Vamos jogar?</h1><p>Chame alguém e entre em campo.</p></div><div className="mascot">⚽</div></section><section className="actions"><button className="play" onClick={create} disabled={creating}><Plus/>{creating?'Criando…':'Criar partida'}<span>Abra uma sala privada</span></button><button className="join" onClick={()=>setScreen('join')}><Users/>Entrar com código<span>Jogue com um amigo</span></button></section><h2>Seu time</h2><TeamCard team={team} onClick={()=>setScreen('team')}/><div className="quick"><button onClick={()=>setScreen('history')}><History/>Histórico</button><button onClick={()=>setScreen('team')}><Settings/>Editar time</button></div></main></>}
 {!restoring&&screen==='team'&&<main className="page narrow">{team&&nav('home')}<TeamEditor initial={team||newTeam()} saving={savingTeam} onSave={persistTeam}/></main>}
 {!restoring&&screen==='join'&&<main className="page narrow">{nav('home')}<Join initialCode={pendingCode} joining={joining} onJoin={c=>{setPendingCode('');return join(c)}}/></main>}
 {!restoring&&screen==='lobby'&&room&&<Lobby room={room} userId={localStorage.getItem('token')!.slice(4)} ws={ws} back={leaveRoom}/>}
 {!restoring&&screen==='game'&&room?.match&&<GameField room={room} userId={localStorage.getItem('token')!.slice(4)} send={m=>ws?.send(JSON.stringify(m))}/>} 
 {!restoring&&screen==='result'&&room?.match&&<Result room={room} userId={localStorage.getItem('token')!.slice(4)} send={m=>ws?.send(JSON.stringify(m))} home={leaveRoom}/>}
 {!restoring&&screen==='history'&&<main className="page narrow">{nav('home')}<HistoryView/></main>}
 </div>}

function Header({user,onLogout}:{user:string;onLogout:()=>void}){return <header><div className="brand"><i>MF</i><b>Manu <span>Fut</span></b></div><div className="profile"><span>{user[0]?.toUpperCase()}</span><b>{user}</b><Volume2/><button className="ghost" aria-label="Sair" title="Sair" onClick={onLogout}><LogOut/></button></div></header>}
function Auth({onLogin}:{onLogin:(s:string)=>void}){const[n,setN]=useState('');return <main className="auth"><div className="brand big"><i>MF</i><b>Manu <span>Fut</span></b></div><div className="auth-shell"><div className="auth-hero"><img src="/manu-fut-hero.png" alt="Crianças jogando futebol de botão no Manu Fut"/></div><div className="auth-card"><div className="ball">⚽</div><h1>Entre em campo!</h1><p>Futebol de botão para jogar com quem você gosta.</p><label>Como podemos te chamar?</label><input autoFocus maxLength={24} placeholder="Seu nome" value={n} onChange={e=>setN(e.target.value)} onKeyDown={e=>e.key==='Enter'&&onLogin(n)}/><button className="primary" onClick={()=>onLogin(n)}>Jogar agora <Gamepad2/></button><small>Ambiente familiar, simples e seguro.</small></div></div></main>}
function TeamCard({team,onClick}:{team:Team;onClick:()=>void}){return <button className="team-card" onClick={onClick} style={{'--team':team.primary}as React.CSSProperties}><Shield/><div><b>{team.name}</b><span>{team.short} • 4 jogadores</span><div className="avatars">{team.players.map((p,i)=><i key={i} style={{background:i%2?team.secondary:team.primary}}>{team.playerPhotos[i]?<img src={team.playerPhotos[i]} alt=""/>:p[0]}</i>)}</div></div><Settings/></button>}
function TeamEditor({initial,saving,onSave}:{initial:Team;saving?:boolean;onSave:(t:Team)=>void}){const[t,setT]=useState(initial);const[photoError,setPhotoError]=useState('');const valid=t.name.trim().length>=2&&t.short.trim().length===3&&t.players.every(p=>p.trim().length>=2);const choosePhoto=async(file:File|undefined,index:number)=>{if(!file)return;setPhotoError('');try{const photo=await resizePhoto(file);setT(current=>{const playerPhotos=[...current.playerPhotos];playerPhotos[index]=photo;return{...current,playerPhotos}})}catch(error){setPhotoError((error as Error).message)}};return <div className="panel"><span className="eyebrow">PERSONALIZAÇÃO</span><h1>Monte seu time</h1><div className="crest" style={{background:t.primary}}><Shield/></div><div className="grid2"><label>Nome do time<input value={t.name} maxLength={28} onChange={e=>setT({...t,name:e.target.value})}/></label><label>Sigla<input value={t.short} maxLength={3} onChange={e=>setT({...t,short:e.target.value.toUpperCase()})}/></label><label>Cor principal<input type="color" value={t.primary} onChange={e=>setT({...t,primary:e.target.value})}/></label><label>Cor secundária<input type="color" value={t.secondary} onChange={e=>setT({...t,secondary:e.target.value})}/></label></div><h2>Jogadores</h2><p className="photo-help">Toque na foto para personalizar cada botão.</p>{t.players.map((p,i)=><div className="player" key={i}><label className="photo-picker" title="Escolher foto"><i style={{background:i%2?t.secondary:t.primary}}>{t.playerPhotos[i]?<img src={t.playerPhotos[i]} alt={`Foto de ${p||'jogador'}`}/>:p[0]?.toUpperCase()}</i><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>choosePhoto(e.target.files?.[0],i)}/><small>Foto</small></label><span>{i===3?'Goleiro':`Linha ${i+1}`}</span><input aria-label={`Nome do ${i===3?'goleiro':`jogador ${i+1}`}`} value={p} maxLength={20} onChange={e=>{const players=[...t.players];players[i]=e.target.value;setT({...t,players})}}/>{t.playerPhotos[i]&&<button className="remove-photo" type="button" onClick={()=>{const playerPhotos=[...t.playerPhotos];playerPhotos[i]='';setT({...t,playerPhotos})}}>Remover</button>}</div>)}{photoError&&<p className="form-error">{photoError}</p>}<button className="primary" disabled={!valid||saving} onClick={()=>onSave({...t,name:t.name.trim(),short:t.short.trim(),players:t.players.map(p=>p.trim())})}>{saving?'Salvando…':'Salvar time'}</button></div>}
function Join({onJoin,joining,initialCode=''}:{onJoin:(s:string)=>void;joining?:boolean;initialCode?:string}){const[c,setC]=useState(initialCode);return <div className="panel centered"><div className="icon"><Users/></div><h1>Entrar na partida</h1><p>Use o link de convite do anfitrião ou o código, no mesmo endereço de rede.</p><input className="code-input" maxLength={6} placeholder="ABC123" value={c} onChange={e=>setC(e.target.value.toUpperCase().replace(/[^A-F0-9]/g,''))}/><button className="primary" disabled={c.length<6||joining} onClick={()=>onJoin(c)}>{joining?'Entrando…':'Entrar na sala'}</button><p className="join-hint">Servidor atual: <b>{shareOrigin}</b></p></div>}
function HistoryView(){const[rooms,setRooms]=useState<Room[]|null>(null);const[error,setError]=useState('');useEffect(()=>{getHistory().then(setRooms).catch(e=>setError((e as Error).message))},[]);if(error)return <div className="panel empty"><History size={44}/><h1>Histórico</h1><p>{error}</p></div>;if(!rooms)return <div className="panel empty"><p>Carregando histórico...</p></div>;if(!rooms.length)return <div className="panel empty"><History size={44}/><h1>Histórico</h1><p>Suas partidas concluídas aparecerão aqui.</p></div>;return <div className="panel"><h1>Histórico</h1>{rooms.map(room=><div className="history-row" key={room.code}><b>{Object.values(room.participants).map(p=>p.team_name).join(' x ')}</b><span>{Object.values(room.match?.score||{}).join(' - ')}</span></div>)}</div>}
function Lobby({room,userId,ws,back}:{room:Room;userId:string;ws:WebSocket|null;back:()=>void}){const me=room.participants[userId];const link=inviteUrl(room.code);const localOnly=/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/i.test(shareOrigin);return <main className="page lobby"> <button className="back" onClick={back}><ArrowLeft/> Sair da sala</button><div className="status-dot">SALA PRIVADA</div><h1>Prepare o time!</h1><p>Convide um amigo e marque-se como pronto.</p>{localOnly&&<p className="network-hint">Para jogar em outro computador, acesse pelo IP da rede (ex.: <b>http://192.168.1.5:5173</b>) e copie o convite de lá.</p>}<button className="invite" onClick={()=>navigator.clipboard.writeText(link)}><span>Link de convite<b>{room.code}</b></span><Copy/>Copiar link</button><p className="invite-url">{link}</p><div className="versus">{Object.values(room.participants).map((p,i)=><div className={`player-slot ${p.ready?'ready':''}`} key={p.id}><div className="crest" style={{background:p.primary}}><Shield/></div><b>{p.team_name}</b><span>{p.name}{p.id===userId?' (você)':''}</span><em>{p.ready?'PRONTO':'ESCOLHENDO'}</em>{i===0&&<strong>VS</strong>}</div>)}{Object.keys(room.participants).length<2&&<div className="player-slot waiting"><div className="pulse"><Users/></div><b>Aguardando...</b><span>Compartilhe o código</span></div>}</div><button className="primary ready-btn" onClick={()=>ws?.send(JSON.stringify({type:'ready',ready:!me.ready}))}>{me.ready?'Cancelar':'Estou pronto!'}</button></main>}
function Result({room,userId,send,home}:{room:Room;userId:string;send:(x:object)=>void;home:()=>void}){const m=room.match!,ids=Object.keys(room.participants),winner=m.winner_id;return <main className="result"><div className="trophy">🏆</div><span className="eyebrow">FIM DE JOGO</span><h1>{!winner?'Empate!':winner===userId?'Você venceu!':'Boa partida!'}</h1><p className="result-reason">{winner?'Quem fez mais gols vence.':'Empate no placar — a partida terminou quando acabaram as jogadas.'}</p><div className="final-score"><div><b>{room.participants[ids[0]].team_name}</b><strong>{m.score[ids[0]]}</strong></div><span>×</span><div><strong>{m.score[ids[1]]}</strong><b>{room.participants[ids[1]].team_name}</b></div></div><button className="primary" onClick={()=>send({type:'rematch'})}>Jogar novamente</button><button className="ghost" onClick={home}>Voltar ao início</button></main>}
