import{useEffect,useState}from'react';import{ArrowLeft,Clock3,Copy,Gamepad2,History,LogOut,Plus,Settings,Shield,Users,Volume2}from'lucide-react';
import{createRoom,joinRoom,wsUrl}from'./api';import type{Room,Team}from'./types';import{GameField}from'./GameField';

const defaultTeam:Team={name:'Estrelas FC',short:'EFC',primary:'#6d28d9',secondary:'#fbbf24',players:['Manu','Léo','Bia','Gabi']};
type Screen='auth'|'home'|'team'|'join'|'lobby'|'game'|'result'|'history';
export function App(){
 const[user,setUser]=useState(()=>localStorage.getItem('name')||'');const[screen,setScreen]=useState<Screen>(user?'home':'auth');const[team,setTeam]=useState<Team>(()=>JSON.parse(localStorage.getItem('team')||JSON.stringify(defaultTeam)));const[room,setRoom]=useState<Room|null>(null);const[ws,setWs]=useState<WebSocket|null>(null);const[toast,setToast]=useState('');
 useEffect(()=>{if(!room||!['lobby','game','result'].includes(screen))return;let socket:WebSocket;let retry:number;const connect=()=>{socket=new WebSocket(wsUrl(room.code));socket.onopen=()=>setWs(socket);socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='state'){setRoom(m.room);setScreen(m.room.status==='finished'?'result':m.room.match?'game':'lobby')}if(m.type==='error')flash(m.message)};socket.onclose=()=>retry=window.setTimeout(connect,1200)};connect();return()=>{clearTimeout(retry);socket?.close()};},[room?.code]);
 const flash=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2500)};
 const login=(name:string)=>{const clean=name.trim();if(clean.length<2)return;localStorage.setItem('name',clean);localStorage.setItem('token',`dev-${crypto.randomUUID()}`);setUser(clean);setScreen('home')};
 const create=async()=>{try{const r=await createRoom(user,team);setRoom(r);setScreen('lobby')}catch(e){flash((e as Error).message)}};
 const join=async(code:string)=>{try{const r=await joinRoom(code.toUpperCase(),user,team);setRoom(r);setScreen('lobby')}catch(e){flash((e as Error).message)}};
 const nav=(s:Screen)=><button className="back" onClick={()=>setScreen(s)}><ArrowLeft/> Voltar</button>;
 return <div className="app">{toast&&<div className="toast">{toast}</div>}
 {screen==='auth'&&<Auth onLogin={login}/>} {screen==='home'&&<><Header user={user}/><main className="page"><section className="hello"><div><span className="eyebrow">OLÁ, {user.toUpperCase()}!</span><h1>Vamos jogar?</h1><p>Chame alguém e entre em campo.</p></div><div className="mascot">⚽</div></section><section className="actions"><button className="play" onClick={create}><Plus/>Criar partida<span>Abra uma sala privada</span></button><button className="join" onClick={()=>setScreen('join')}><Users/>Entrar com código<span>Jogue com um amigo</span></button></section><h2>Seu time</h2><TeamCard team={team} onClick={()=>setScreen('team')}/><div className="quick"><button onClick={()=>setScreen('history')}><History/>Histórico</button><button onClick={()=>setScreen('team')}><Settings/>Editar time</button></div></main></>}
 {screen==='team'&&<main className="page narrow">{nav('home')}<TeamEditor initial={team} onSave={t=>{setTeam(t);localStorage.setItem('team',JSON.stringify(t));setScreen('home')}}/></main>}
 {screen==='join'&&<main className="page narrow">{nav('home')}<Join onJoin={join}/></main>}
 {screen==='lobby'&&room&&<Lobby room={room} userId={localStorage.getItem('token')!.slice(4)} ws={ws} back={()=>setScreen('home')}/>} 
 {screen==='game'&&room?.match&&<GameField room={room} userId={localStorage.getItem('token')!.slice(4)} send={m=>ws?.send(JSON.stringify(m))}/>} 
 {screen==='result'&&room?.match&&<Result room={room} userId={localStorage.getItem('token')!.slice(4)} send={m=>ws?.send(JSON.stringify(m))} home={()=>{setRoom(null);setScreen('home')}}/>}
 {screen==='history'&&<main className="page narrow">{nav('home')}<div className="panel empty"><History size={44}/><h1>Histórico</h1><p>Suas partidas concluídas aparecerão aqui.</p></div></main>}
 </div>}

function Header({user}:{user:string}){return <header><div className="brand"><i>MF</i><b>Manu <span>Fut</span></b></div><div className="profile"><span>{user[0]?.toUpperCase()}</span><b>{user}</b><Volume2/><LogOut/></div></header>}
function Auth({onLogin}:{onLogin:(s:string)=>void}){const[n,setN]=useState('');return <main className="auth"><div className="brand big"><i>MF</i><b>Manu <span>Fut</span></b></div><div className="auth-card"><div className="ball">⚽</div><h1>Entre em campo!</h1><p>Futebol de botão para jogar com quem você gosta.</p><label>Como podemos te chamar?</label><input autoFocus maxLength={24} placeholder="Seu nome" value={n} onChange={e=>setN(e.target.value)} onKeyDown={e=>e.key==='Enter'&&onLogin(n)}/><button className="primary" onClick={()=>onLogin(n)}>Jogar agora <Gamepad2/></button><small>Ambiente familiar, simples e seguro.</small></div></main>}
function TeamCard({team,onClick}:{team:Team;onClick:()=>void}){return <button className="team-card" onClick={onClick} style={{'--team':team.primary}as React.CSSProperties}><Shield/><div><b>{team.name}</b><span>{team.short} • 4 jogadores</span><div className="avatars">{team.players.map((p,i)=><i key={p} style={{background:i%2?team.secondary:team.primary}}>{p[0]}</i>)}</div></div><Settings/></button>}
function TeamEditor({initial,onSave}:{initial:Team;onSave:(t:Team)=>void}){const[t,setT]=useState(initial);return <div className="panel"><span className="eyebrow">PERSONALIZAÇÃO</span><h1>Monte seu time</h1><div className="crest" style={{background:t.primary}}><Shield/></div><div className="grid2"><label>Nome do time<input value={t.name} maxLength={28} onChange={e=>setT({...t,name:e.target.value})}/></label><label>Sigla<input value={t.short} maxLength={3} onChange={e=>setT({...t,short:e.target.value.toUpperCase()})}/></label><label>Cor principal<input type="color" value={t.primary} onChange={e=>setT({...t,primary:e.target.value})}/></label><label>Cor secundária<input type="color" value={t.secondary} onChange={e=>setT({...t,secondary:e.target.value})}/></label></div><h2>Jogadores</h2>{t.players.map((p,i)=><label className="player" key={i}><i style={{background:i%2?t.secondary:t.primary}}>{p[0]}</i><span>{i===3?'Goleiro':`Linha ${i+1}`}</span><input value={p} maxLength={20} onChange={e=>{const players=[...t.players];players[i]=e.target.value;setT({...t,players})}}/></label>)}<button className="primary" onClick={()=>onSave(t)}>Salvar time</button></div>}
function Join({onJoin}:{onJoin:(s:string)=>void}){const[c,setC]=useState('');return <div className="panel centered"><div className="icon"><Users/></div><h1>Entrar na partida</h1><p>Digite o código que seu amigo compartilhou.</p><input className="code-input" maxLength={6} placeholder="ABC123" value={c} onChange={e=>setC(e.target.value.toUpperCase())}/><button className="primary" disabled={c.length<6} onClick={()=>onJoin(c)}>Entrar na sala</button></div>}
function Lobby({room,userId,ws,back}:{room:Room;userId:string;ws:WebSocket|null;back:()=>void}){const me=room.participants[userId];return <main className="page lobby"> <button className="back" onClick={back}><ArrowLeft/> Sair da sala</button><div className="status-dot">SALA PRIVADA</div><h1>Prepare o time!</h1><p>Convide um amigo e marque-se como pronto.</p><button className="invite" onClick={()=>navigator.clipboard.writeText(location.origin+`?room=${room.code}`)}><span>Código da sala<b>{room.code}</b></span><Copy/>Copiar convite</button><div className="versus">{Object.values(room.participants).map((p,i)=><div className={`player-slot ${p.ready?'ready':''}`} key={p.id}><div className="crest" style={{background:p.primary}}><Shield/></div><b>{p.team_name}</b><span>{p.name}{p.id===userId?' (você)':''}</span><em>{p.ready?'PRONTO':'ESCOLHENDO'}</em>{i===0&&<strong>VS</strong>}</div>)}{Object.keys(room.participants).length<2&&<div className="player-slot waiting"><div className="pulse"><Users/></div><b>Aguardando...</b><span>Compartilhe o código</span></div>}</div><button className="primary ready-btn" onClick={()=>ws?.send(JSON.stringify({type:'ready',ready:!me.ready}))}>{me.ready?'Cancelar':'Estou pronto!'}</button></main>}
function Result({room,userId,send,home}:{room:Room;userId:string;send:(x:object)=>void;home:()=>void}){const m=room.match!,ids=Object.keys(room.participants),winner=m.winner_id;return <main className="result"><div className="trophy">🏆</div><span className="eyebrow">FIM DE JOGO</span><h1>{!winner?'Empate!':winner===userId?'Você venceu!':'Boa partida!'}</h1><div className="final-score"><div><b>{room.participants[ids[0]].team_name}</b><strong>{m.score[ids[0]]}</strong></div><span>×</span><div><strong>{m.score[ids[1]]}</strong><b>{room.participants[ids[1]].team_name}</b></div></div><button className="primary" onClick={()=>send({type:'rematch'})}>Jogar novamente</button><button className="ghost" onClick={home}>Voltar ao início</button></main>}
