import{useEffect,useRef,useState}from'react';import{Flag,Volume2}from'lucide-react';import type{Room}from'./types';
export function GameField({room,userId,send}:{room:Room;userId:string;send:(m:object)=>void}){const canvas=useRef<HTMLCanvasElement>(null),drag=useRef<{id:string;x:number;y:number}|null>(null),[aim,setAim]=useState<{x:number;y:number;tx:number;ty:number}|null>(null),[now,setNow]=useState(Date.now());const m=room.match!,ids=Object.keys(room.participants),myTurn=m.turn_player_id===userId;
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(id)},[]);
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d')!,dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);const sx=w/1000,sy=h/600;ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(255,255,255,.8)';ctx.lineWidth=3;ctx.strokeRect(18*sx,18*sy,964*sx,564*sy);ctx.beginPath();ctx.moveTo(500*sx,18*sy);ctx.lineTo(500*sx,582*sy);ctx.stroke();ctx.beginPath();ctx.arc(500*sx,300*sy,82*Math.min(sx,sy),0,Math.PI*2);ctx.stroke();for(const x of [18,982]){ctx.strokeRect((x===18?18:842)*sx,190*sy,140*sx,220*sy)}
 const draw=(p:any)=>{const x=p.position.x*sx,y=p.position.y*sy,r=p.radius*Math.min(sx,sy);ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);if(p.role==='ball'){ctx.fillStyle='#fff';ctx.fill();ctx.font=`${r*1.5}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('⚽',x,y);return}const owner=room.participants[p.owner_id];ctx.fillStyle=owner.primary;ctx.fill();ctx.lineWidth=5;ctx.strokeStyle=owner.secondary;ctx.stroke();ctx.fillStyle='#fff';ctx.font=`bold ${r*.8}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(owner.name[0].toUpperCase(),x,y)};m.pieces.forEach(draw);draw(m.ball);if(aim){ctx.setLineDash([8,8]);ctx.strokeStyle='#fde047';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(aim.x,aim.y);ctx.lineTo(aim.tx,aim.ty);ctx.stroke();ctx.setLineDash([])}},[room,aim]);
 const point=(e:React.PointerEvent)=>{const r=canvas.current!.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top,sx:1000/r.width,sy:600/r.height}};
 const down=(e:React.PointerEvent)=>{if(!myTurn)return;const p=point(e),piece=m.pieces.find(v=>v.owner_id===userId&&Math.hypot(v.position.x-p.x*p.sx,v.position.y-p.y*p.sy)<v.radius*1.5);if(piece){drag.current={id:piece.id,x:p.x,y:p.y};setAim({x:p.x,y:p.y,tx:p.x,ty:p.y});canvas.current!.setPointerCapture(e.pointerId)}};
 const move=(e:React.PointerEvent)=>{if(!drag.current)return;const p=point(e);setAim({x:drag.current.x,y:drag.current.y,tx:p.x,ty:p.y})};
 const up=(e:React.PointerEvent)=>{if(!drag.current)return;const p=point(e),dx=drag.current.x-p.x,dy=drag.current.y-p.y,dist=Math.hypot(dx,dy);if(dist>8)send({type:'move',piece_id:drag.current.id,direction:{x:dx,y:dy},force:Math.min(1,dist/140),sequence:m.sequence+1});drag.current=null;setAim(null)};
 const seconds=Math.max(0,Math.ceil((m.turn_deadline*1000-now)/1000));return <main className="game"><div className="scorebar"><div><i style={{background:room.participants[ids[0]].primary}}>{room.participants[ids[0]].name[0]}</i><b>{room.participants[ids[0]].team_name}</b></div><strong>{m.score[ids[0]]} <span>×</span> {m.score[ids[1]]}</strong><div><b>{room.participants[ids[1]].team_name}</b><i style={{background:room.participants[ids[1]].primary}}>{room.participants[ids[1]].name[0]}</i></div></div><div className="turn"><span className={myTurn?'active':''}>{myTurn?'SUA VEZ!':'VEZ DO ADVERSÁRIO'}</span><b>{seconds}s</b><small>{m.turns_left} jogadas restantes</small></div><div className="field-wrap"><canvas ref={canvas} onPointerDown={down} onPointerMove={move} onPointerUp={up}/></div><div className="game-hint">{myTurn?'Puxe uma peça para trás e solte para chutar':'Aguarde a jogada do adversário'} </div><div className="game-tools"><button onClick={()=>send({type:'forfeit'})}><Flag/>Desistir</button><button><Volume2/>Som</button></div></main>}
